# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3103c8a9e977a258df22e8f590bfdee1e165ca9ad0a54ec54b28fc4a538613cc9bbc95b114109f9d9f66f46716d2ed7255939bc7a375bba505edb9e115bfcab6

test:
  secret_key_base: a72433d98f12ee242490207921de7eab278e18faa740a67cb4764500513be712469e5d5151c0499c9aa9cf9011d31bd1a64eda2b7aae910d9f4753634f0f27b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
